export const endpoints = {
  products: '/products',
  productById: (id) => `/products/${id}`,
  cart: '/cart',
  cartMerge: '/cart/merge',
  cartAdd: '/cart/add',
  cartUpdateQuantity: '/cart/update-quantity',
  cartRemove: (productId) => `/cart/remove/${productId}`,
  cartClear: '/cart/clear',
  wishlist: '/customer/wishlist',
  wishlistToggle: '/wishlist/toggle',
  wishlistRemove: (productId) => `/customer/wishlist/${productId}`,
  storeDistricts: '/store/districts',
  storeShippingQuote: '/store/shipping-quote',
  orders: '/orders',
  orderCancel: (id) => `/orders/${id}/cancel`,
  profile: '/profile',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    account: '/auth/account',
  },
};
