export const endpoints = {
  products: '/products',
  productSearch: '/products/search',
  productById: (id) => `/products/${id}`,
  cart: '/cart',
  cartMerge: '/cart/merge',
  cartAdd: '/cart/add',
  cartUpdateQuantity: '/cart/update-quantity',
  cartRemove: (productId) => `/cart/remove/${productId}`,
  cartClear: '/cart/clear',
  wishlist: '/customer/wishlist',
  wishlistToggle: '/wishlist/toggle',
  wishlistRemove: (productId) => `/customer/wishlist/${productId}`,
  storeDistricts: '/store/districts',
  storeShippingQuote: '/store/shipping-quote',
  storeBanners: '/store/banners',
  storeFlashSale: '/store/flash-sale',
  categoriesNavbar: '/categories/navbar',
  orders: '/orders',
  orderCancel: (id) => `/orders/${id}/cancel`,
  reviews: '/reviews',
  reviewsByProduct: (id) => `/reviews/${id}`,
  profile: '/customer/profile',
  updateAvatar: '/customer/update-avatar',
  convertPoints: '/customer/convert-points',
  requestContactOtp: '/customer/profile/request-contact-otp',
  verifyContactOtp: '/customer/profile/verify-contact-otp',
  notes: '/notes',
  sessions: '/auth/sessions',
  sessionById: (id) => `/auth/sessions/${id}`,
  logoutOtherSessions: '/auth/sessions/logout-others',
  couponsApply: '/coupons/apply',
  couponsActiveCheck: '/coupons/active-check',
  paymentMethods: '/payments/methods',
  paymentsInitiate: '/payments/initiate',
  orderPaymentProof: (id) => `/orders/${id}/payment-proof`,
  customerAddresses: '/customer/addresses',
  customerAddressById: (id) => `/customer/addresses/${id}`,
  customerChangePassword: '/customer/change-password',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    account: '/auth/account',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    resendVerification: '/auth/resend-verification',
  },
};
