-- Phase 3: Global tax settings + order tax snapshots
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "taxSettings" JSONB NOT NULL DEFAULT '{}';

ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "vatRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "taxAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "taxableAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "priceTaxMode" TEXT NOT NULL DEFAULT 'EXCLUSIVE';
